# Generated by Django 4.2.5 on 2023-09-16 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0002_trainingrequirement"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completion_date", models.DateField()),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="training.employee",
                    ),
                ),
                (
                    "training_requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="training.trainingrequirement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainingAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_date", models.DateField()),
                ("due_date", models.DateField()),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="training.employee",
                    ),
                ),
                (
                    "training_requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="training.trainingrequirement",
                    ),
                ),
            ],
        ),
    ]
